---
transform:
  # transform parameters
  min_size: 800
  max_size: 1333

RPN:
  # RPN parameters
  rpn_pre_nms_top_n_train: 2000
  rpn_pre_nms_top_n_test: 1000
  rpn_post_nms_top_n_train: 2000
  rpn_post_nms_top_n_test: 1000
  rpn_nms_thresh: 0.7
  rpn_fg_iou_thresh: 0.7
  rpn_bg_iou_thresh: 0.3
  rpn_batch_size_per_image: 256
  rpn_positive_fraction: 0.5
  rpn_score_thresh: 0.0
  
ROIHeads:
  # Box parameters (Detection part, RoIHeads)
  box_score_thresh: 0.10  # Minimum score to output the detection
  box_nms_thresh: 0.45  # Boxes with greater IoU than the thr and lower score are removed.
  box_detections_per_img: 100
  box_fg_iou_thresh: 0.5
  box_bg_iou_thresh: 0.5
  box_batch_size_per_image: 512 # Defines the final number of proposals per image selected inside ROI to apply pooling
  box_positive_fraction: 0.25  # ORIGINAL 0.25